---
format_version: '13'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git

project_type: flutter

# Trigger налаштування
triggers:
  push:
    - branch: main
      workflow: android_dev
    - branch: staging
      workflow: android_staging
    - branch: production
      workflow: android_prod
  pull_request:
    - source_branch: "*"
      workflow: android_dev

# Workflows

workflows:
  android_dev:
    description: Build Android APK (DEV flavor) для Firebase App Distribution
    steps:
    - git-clone@8:
        inputs:
        - clone_depth: '0'
        - fetch_tags: 'yes'
    - flutter-installer@0:
        inputs:
        - version: 3.35.3
        - is_update: 'false'
    - restore-dart-cache@2: {}
    - script@1:
        title: Flutter packages get
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            flutter pub get
    - script@1:
        title: Generate env files
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            
            echo " Creating .env files..."
            
            cat > .env.dev << EOF
            apiUrl=$DEV_API_URL
            firebaseApiKey=$DEV_FIREBASE_API_KEY
            EOF
            
            cat > .env.staging << EOF
            apiUrl=$STAGING_API_URL
            firebaseApiKey=$STAGING_FIREBASE_API_KEY
            EOF
            
            cat > .env.prod << EOF
            apiUrl=$PROD_API_URL
            firebaseApiKey=$PROD_FIREBASE_API_KEY
            EOF
            
            echo " .env files created"
            
            echo " Running build_runner..."
            dart run build_runner build --delete-conflicting-outputs
            
            echo " Code generation completed"
    - script@1:
        title: Get Debug SHA-1
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            
            echo " Getting SHA-1 fingerprint..."
            
            KEYSTORE_PATH="$HOME/.android/debug.keystore"
            
            if [ -f "$KEYSTORE_PATH" ]; then
                SHA1=$(keytool -list -v -keystore "$KEYSTORE_PATH" -alias androiddebugkey -storepass android -keypass android 2>/dev/null | grep SHA1 | awk '{print $2}')
                echo "SHA-1: $SHA1"
                envman add --key BITRISE_SHA1 --value "$SHA1"
            fi
    - save-dart-cache@1: {}
    - script@1:
        title: Build Android APK (DEV Debug)
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            
            flutter build apk --debug --flavor dev -t lib/main_dev.dart
            
            APK_PATH="build/app/outputs/flutter-apk/app-dev-debug.apk"
            
            if [ -f "$APK_PATH" ]; then
                envman add --key ANDROID_APK_PATH --value "$BITRISE_SOURCE_DIR/$APK_PATH"
                cp "$APK_PATH" "$BITRISE_DEPLOY_DIR/CookingBook-DEV.apk"
                echo " APK built"
            else
                exit 1
            fi
    - script@1:
        title: Firebase App Distribution (DEV)
        is_always_run: false
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            
            if [ -z "$FIREBASE_TOKEN" ] || [ -z "$FIREBASE_APP_ID_ANDROID" ]; then
                echo " Missing Firebase config"
                exit 1
            fi
            
            npm install -g firebase-tools
            
            FIREBASE_TOKEN="$FIREBASE_TOKEN" firebase appdistribution:distribute "$ANDROID_APK_PATH" \
              --app "$FIREBASE_APP_ID_ANDROID" \
              --token "$FIREBASE_TOKEN" \
              --testers "jetcraker@gmail.com" \
              --release-notes "DEV Build #$BITRISE_BUILD_NUMBER"
    - deploy-to-bitrise-io@2:
        inputs:
        - notify_user_groups: none

  android_staging:
    description: Build Android APK (STAGING flavor)
    steps:
    - git-clone@8: {}
    - flutter-installer@0:
        inputs:
        - version: 3.35.3
    - restore-dart-cache@2: {}
    - script@1:
        title: Flutter pub get
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            flutter pub get
    - script@1:
        title: Generate env files
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            
            cat > .env.dev << EOF
            apiUrl=$DEV_API_URL
            firebaseApiKey=$DEV_FIREBASE_API_KEY
            EOF
            
            cat > .env.staging << EOF
            apiUrl=$STAGING_API_URL
            firebaseApiKey=$STAGING_FIREBASE_API_KEY
            EOF
            
            cat > .env.prod << EOF
            apiUrl=$PROD_API_URL
            firebaseApiKey=$PROD_FIREBASE_API_KEY
            EOF
            
            dart run build_runner build --delete-conflicting-outputs
    - save-dart-cache@1: {}
    - script@1:
        title: Build STAGING APK
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            
            flutter build apk --release --flavor staging -t lib/main_staging.dart
            
            APK_PATH="build/app/outputs/flutter-apk/app-staging-release.apk"
            
            if [ -f "$APK_PATH" ]; then
                envman add --key ANDROID_APK_PATH --value "$BITRISE_SOURCE_DIR/$APK_PATH"
                cp "$APK_PATH" "$BITRISE_DEPLOY_DIR/CookingBook-STAGING.apk"
            else
                exit 1
            fi
    - script@1:
        title: Firebase Distribution
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            
            npm install -g firebase-tools
            
            FIREBASE_TOKEN="$FIREBASE_TOKEN" firebase appdistribution:distribute "$ANDROID_APK_PATH" \
              --app "$FIREBASE_APP_ID_ANDROID" \
              --token "$FIREBASE_TOKEN" \
              --testers "jetcraker@gmail.com" \
              --release-notes "STAGING Build #$BITRISE_BUILD_NUMBER"
    - deploy-to-bitrise-io@2:
        inputs:
        - notify_user_groups: none

  android_prod:
    description: Build Android APK (PROD flavor)
    steps:
    - git-clone@8: {}
    - flutter-installer@0:
        inputs:
        - version: 3.35.3
    - restore-dart-cache@2: {}
    - script@1:
        title: Flutter pub get
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            flutter pub get
    - script@1:
        title: Generate env files
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            
            cat > .env.dev << EOF
            apiUrl=$DEV_API_URL
            firebaseApiKey=$DEV_FIREBASE_API_KEY
            EOF
            
            cat > .env.staging << EOF
            apiUrl=$STAGING_API_URL
            firebaseApiKey=$STAGING_FIREBASE_API_KEY
            EOF
            
            cat > .env.prod << EOF
            apiUrl=$PROD_API_URL
            firebaseApiKey=$PROD_FIREBASE_API_KEY
            EOF
            
            dart run build_runner build --delete-conflicting-outputs
    - save-dart-cache@1: {}
    - script@1:
        title: Build PROD APK
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            
            flutter build apk --release --flavor prod -t lib/main_prod.dart
            
            APK_PATH="build/app/outputs/flutter-apk/app-prod-release.apk"
            
            if [ -f "$APK_PATH" ]; then
                envman add --key ANDROID_APK_PATH --value "$BITRISE_SOURCE_DIR/$APK_PATH"
                cp "$APK_PATH" "$BITRISE_DEPLOY_DIR/CookingBook-PROD.apk"
            else
                exit 1
            fi
    - script@1:
        title: Firebase Distribution
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            
            npm install -g firebase-tools
            
            FIREBASE_TOKEN="$FIREBASE_TOKEN" firebase appdistribution:distribute "$ANDROID_APK_PATH" \
              --app "$FIREBASE_APP_ID_ANDROID" \
              --token "$FIREBASE_TOKEN" \
              --testers "jetcraker@gmail.com" \
              --release-notes "PROD Build #$BITRISE_BUILD_NUMBER"
    - deploy-to-bitrise-io@2:
        inputs:
        - notify_user_groups: none

app:
  envs:
  - BITRISE_FLUTTER_PROJECT_LOCATION: "."
    opts:
      is_expand: false
  - FLUTTER_VERSION: stable
    opts:
      is_expand: false

meta:
  bitrise.io:
    stack: linux-docker-android-22.04