// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMzXoPygbk-DLSTRysJU5qiiQdSpN8NOI',
    appId: '1:86476150805:web:25a08246a05f9c3ae9561c',
    messagingSenderId: '86476150805',
    projectId: 'cooking-book-2b35e',
    authDomain: 'cooking-book-2b35e.firebaseapp.com',
    storageBucket: 'cooking-book-2b35e.firebasestorage.app',
    measurementId: 'G-3PEDY69SBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7XJ4uEBgxPCzW7becSYhUwwKjBp2mxlw',
    appId: '1:86476150805:android:2a8f3ee4551f2d13e9561c',
    messagingSenderId: '86476150805',
    projectId: 'cooking-book-2b35e',
    storageBucket: 'cooking-book-2b35e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzsVkiqtZI-1P2121jj4JNC8qq-ZAf4po',
    appId: '1:86476150805:ios:9ec3d120a8ca87dae9561c',
    messagingSenderId: '86476150805',
    projectId: 'cooking-book-2b35e',
    storageBucket: 'cooking-book-2b35e.firebasestorage.app',
    iosBundleId: 'com.example.cookingBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzsVkiqtZI-1P2121jj4JNC8qq-ZAf4po',
    appId: '1:86476150805:ios:9ec3d120a8ca87dae9561c',
    messagingSenderId: '86476150805',
    projectId: 'cooking-book-2b35e',
    storageBucket: 'cooking-book-2b35e.firebasestorage.app',
    iosBundleId: 'com.example.cookingBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMzXoPygbk-DLSTRysJU5qiiQdSpN8NOI',
    appId: '1:86476150805:web:862ebe133320064be9561c',
    messagingSenderId: '86476150805',
    projectId: 'cooking-book-2b35e',
    authDomain: 'cooking-book-2b35e.firebaseapp.com',
    storageBucket: 'cooking-book-2b35e.firebasestorage.app',
    measurementId: 'G-2E287CZKZB',
  );
}
